-- Auto-generated smoke and edge coverage for implemented SQL bridges.
-- Keep deterministic outputs only; no headers; list mode is set by test runner.

select 'SECTION|signature-null-smoke';
select 'SMOKE|p_abs|1|' || typeof(p_abs(NULL));
select 'SMOKE|p_acos|1|' || typeof(p_acos(NULL));
select 'SMOKE|p_asin|1|' || typeof(p_asin(NULL));
select 'SMOKE|p_atan|1|' || typeof(p_atan(NULL));
select 'SMOKE|p_atan2|2|' || typeof(p_atan2(NULL, NULL));
select 'SMOKE|p_beta_cdf|3|' || typeof(p_beta_cdf(NULL, NULL, NULL));
select 'SMOKE|p_binomial_cdf|3|' || typeof(p_binomial_cdf(NULL, NULL, NULL));
select 'SMOKE|p_bit_count|2|' || typeof(p_bit_count(NULL, NULL));
select 'SMOKE|p_bit_length|1|' || typeof(p_bit_length(NULL));
select 'SMOKE|p_bitwise_and|2|' || typeof(p_bitwise_and(NULL, NULL));
select 'SMOKE|p_bitwise_arithmetic_shift_right|2|' || typeof(p_bitwise_arithmetic_shift_right(NULL, NULL));
select 'SMOKE|p_bitwise_left_shift|2|' || typeof(p_bitwise_left_shift(NULL, NULL));
select 'SMOKE|p_bitwise_logical_shift_right|3|' || typeof(p_bitwise_logical_shift_right(NULL, NULL, NULL));
select 'SMOKE|p_bitwise_not|1|' || typeof(p_bitwise_not(NULL));
select 'SMOKE|p_bitwise_or|2|' || typeof(p_bitwise_or(NULL, NULL));
select 'SMOKE|p_bitwise_right_shift|2|' || typeof(p_bitwise_right_shift(NULL, NULL));
select 'SMOKE|p_bitwise_right_shift_arithmetic|2|' || typeof(p_bitwise_right_shift_arithmetic(NULL, NULL));
select 'SMOKE|p_bitwise_shift_left|3|' || typeof(p_bitwise_shift_left(NULL, NULL, NULL));
select 'SMOKE|p_bitwise_xor|2|' || typeof(p_bitwise_xor(NULL, NULL));
select 'SMOKE|p_cauchy_cdf|3|' || typeof(p_cauchy_cdf(NULL, NULL, NULL));
select 'SMOKE|p_cbrt|1|' || typeof(p_cbrt(NULL));
select 'SMOKE|p_ceil|1|' || typeof(p_ceil(NULL));
select 'SMOKE|p_ceiling|1|' || typeof(p_ceiling(NULL));
select 'SMOKE|p_chi_squared_cdf|2|' || typeof(p_chi_squared_cdf(NULL, NULL));
select 'SMOKE|p_chr|1|' || typeof(p_chr(NULL));
select 'SMOKE|p_codepoint|1|' || typeof(p_codepoint(NULL));
select 'SMOKE|p_concat|-1|' || typeof(p_concat(NULL));
select 'SMOKE|p_cos|1|' || typeof(p_cos(NULL));
select 'SMOKE|p_cosh|1|' || typeof(p_cosh(NULL));
select 'SMOKE|p_crc32|1|' || typeof(p_crc32(NULL));
select 'SMOKE|p_degrees|1|' || typeof(p_degrees(NULL));
select 'SMOKE|p_e|0|' || typeof(p_e());
select 'SMOKE|p_ends_with|2|' || typeof(p_ends_with(NULL, NULL));
select 'SMOKE|p_exp|1|' || typeof(p_exp(NULL));
select 'SMOKE|p_f_cdf|3|' || typeof(p_f_cdf(NULL, NULL, NULL));
select 'SMOKE|p_factorial|1|' || typeof(p_factorial(NULL));
select 'SMOKE|p_floor|1|' || typeof(p_floor(NULL));
select 'SMOKE|p_from_base|2|' || typeof(p_from_base(NULL, NULL));
select 'SMOKE|p_from_base32|1|' || typeof(p_from_base32(NULL));
select 'SMOKE|p_from_base64|1|' || typeof(p_from_base64(NULL));
select 'SMOKE|p_from_base64url|1|' || typeof(p_from_base64url(NULL));
select 'SMOKE|p_from_big_endian_32|1|' || typeof(p_from_big_endian_32(NULL));
select 'SMOKE|p_from_big_endian_64|1|' || typeof(p_from_big_endian_64(NULL));
select 'SMOKE|p_from_hex|1|' || typeof(p_from_hex(NULL));
select 'SMOKE|p_from_ieee754_32|1|' || typeof(p_from_ieee754_32(NULL));
select 'SMOKE|p_from_ieee754_64|1|' || typeof(p_from_ieee754_64(NULL));
select 'SMOKE|p_from_utf8|1|' || typeof(p_from_utf8(NULL));
select 'SMOKE|p_from_utf8|2|' || typeof(p_from_utf8(NULL, NULL));
select 'SMOKE|p_gamma_cdf|3|' || typeof(p_gamma_cdf(NULL, NULL, NULL));
select 'SMOKE|p_hamming_distance|2|' || typeof(p_hamming_distance(NULL, NULL));
select 'SMOKE|p_hmac_md5|2|' || typeof(p_hmac_md5(NULL, NULL));
select 'SMOKE|p_hmac_sha1|2|' || typeof(p_hmac_sha1(NULL, NULL));
select 'SMOKE|p_hmac_sha256|2|' || typeof(p_hmac_sha256(NULL, NULL));
select 'SMOKE|p_hmac_sha512|2|' || typeof(p_hmac_sha512(NULL, NULL));
select 'SMOKE|p_infinity|0|' || typeof(p_infinity());
select 'SMOKE|p_inverse_beta_cdf|3|' || typeof(p_inverse_beta_cdf(NULL, NULL, NULL));
select 'SMOKE|p_inverse_binomial_cdf|3|' || typeof(p_inverse_binomial_cdf(NULL, NULL, NULL));
select 'SMOKE|p_inverse_cauchy_cdf|3|' || typeof(p_inverse_cauchy_cdf(NULL, NULL, NULL));
select 'SMOKE|p_inverse_chi_squared_cdf|2|' || typeof(p_inverse_chi_squared_cdf(NULL, NULL));
select 'SMOKE|p_inverse_f_cdf|3|' || typeof(p_inverse_f_cdf(NULL, NULL, NULL));
select 'SMOKE|p_inverse_gamma_cdf|3|' || typeof(p_inverse_gamma_cdf(NULL, NULL, NULL));
select 'SMOKE|p_inverse_laplace_cdf|3|' || typeof(p_inverse_laplace_cdf(NULL, NULL, NULL));
select 'SMOKE|p_inverse_normal_cdf|3|' || typeof(p_inverse_normal_cdf(NULL, NULL, NULL));
select 'SMOKE|p_inverse_poisson_cdf|2|' || typeof(p_inverse_poisson_cdf(NULL, NULL));
select 'SMOKE|p_inverse_t_cdf|2|' || typeof(p_inverse_t_cdf(NULL, NULL));
select 'SMOKE|p_inverse_weibull_cdf|3|' || typeof(p_inverse_weibull_cdf(NULL, NULL, NULL));
select 'SMOKE|p_ip_prefix|2|' || typeof(p_ip_prefix(NULL, NULL));
select 'SMOKE|p_ip_prefix_collapse|1|' || typeof(p_ip_prefix_collapse(NULL));
select 'SMOKE|p_ip_prefix_subnets|2|' || typeof(p_ip_prefix_subnets(NULL, NULL));
select 'SMOKE|p_ip_subnet_max|1|' || typeof(p_ip_subnet_max(NULL));
select 'SMOKE|p_ip_subnet_min|1|' || typeof(p_ip_subnet_min(NULL));
select 'SMOKE|p_ip_subnet_range|1|' || typeof(p_ip_subnet_range(NULL));
select 'SMOKE|p_is_finite|1|' || typeof(p_is_finite(NULL));
select 'SMOKE|p_is_infinite|1|' || typeof(p_is_infinite(NULL));
select 'SMOKE|p_is_nan|1|' || typeof(p_is_nan(NULL));
select 'SMOKE|p_is_private_ip|1|' || typeof(p_is_private_ip(NULL));
select 'SMOKE|p_is_subnet_of|2|' || typeof(p_is_subnet_of(NULL, NULL));
select 'SMOKE|p_jarowinkler_similarity|2|' || typeof(p_jarowinkler_similarity(NULL, NULL));
select 'SMOKE|p_key_sampling_percent|1|' || typeof(p_key_sampling_percent(NULL));
select 'SMOKE|p_laplace_cdf|3|' || typeof(p_laplace_cdf(NULL, NULL, NULL));
select 'SMOKE|p_length|1|' || typeof(p_length(NULL));
select 'SMOKE|p_levenshtein_distance|2|' || typeof(p_levenshtein_distance(NULL, NULL));
select 'SMOKE|p_ln|1|' || typeof(p_ln(NULL));
select 'SMOKE|p_log10|1|' || typeof(p_log10(NULL));
select 'SMOKE|p_log2|1|' || typeof(p_log2(NULL));
select 'SMOKE|p_longest_common_prefix|2|' || typeof(p_longest_common_prefix(NULL, NULL));
select 'SMOKE|p_lower|1|' || typeof(p_lower(NULL));
select 'SMOKE|p_lpad|3|' || typeof(p_lpad(NULL, NULL, NULL));
select 'SMOKE|p_ltrim|1|' || typeof(p_ltrim(NULL));
select 'SMOKE|p_ltrim|2|' || typeof(p_ltrim(NULL, NULL));
select 'SMOKE|p_md5|1|' || typeof(p_md5(NULL));
select 'SMOKE|p_mod|2|' || typeof(p_mod(NULL, NULL));
select 'SMOKE|p_murmur3_x64_128|1|' || typeof(p_murmur3_x64_128(NULL));
select 'SMOKE|p_nan|0|' || typeof(p_nan());
select 'SMOKE|p_normal_cdf|3|' || typeof(p_normal_cdf(NULL, NULL, NULL));
select 'SMOKE|p_normalize|1|' || typeof(p_normalize(NULL));
select 'SMOKE|p_normalize|2|' || typeof(p_normalize(NULL, NULL));
select 'SMOKE|p_pi|0|' || typeof(p_pi());
select 'SMOKE|p_poisson_cdf|2|' || typeof(p_poisson_cdf(NULL, NULL));
select 'SMOKE|p_pow|2|' || typeof(p_pow(NULL, NULL));
select 'SMOKE|p_power|2|' || typeof(p_power(NULL, NULL));
select 'SMOKE|p_radians|1|' || typeof(p_radians(NULL));
select 'SMOKE|p_rand|0|' || typeof(p_rand());
select 'SMOKE|p_random|0|' || typeof(p_random());
select 'SMOKE|p_random|1|' || typeof(p_random(NULL));
select 'SMOKE|p_regexp_extract|2|' || typeof(p_regexp_extract(NULL, NULL));
select 'SMOKE|p_regexp_extract|3|' || typeof(p_regexp_extract(NULL, NULL, NULL));
select 'SMOKE|p_regexp_extract_all|2|' || typeof(p_regexp_extract_all(NULL, NULL));
select 'SMOKE|p_regexp_extract_all|3|' || typeof(p_regexp_extract_all(NULL, NULL, NULL));
select 'SMOKE|p_regexp_like|2|' || typeof(p_regexp_like(NULL, NULL));
select 'SMOKE|p_regexp_replace|2|' || typeof(p_regexp_replace(NULL, NULL));
select 'SMOKE|p_regexp_replace|3|' || typeof(p_regexp_replace(NULL, NULL, NULL));
select 'SMOKE|p_regexp_split|2|' || typeof(p_regexp_split(NULL, NULL));
select 'SMOKE|p_replace|2|' || typeof(p_replace(NULL, NULL));
select 'SMOKE|p_replace|3|' || typeof(p_replace(NULL, NULL, NULL));
select 'SMOKE|p_replace_first|3|' || typeof(p_replace_first(NULL, NULL, NULL));
select 'SMOKE|p_reverse|1|' || typeof(p_reverse(NULL));
select 'SMOKE|p_round|1|' || typeof(p_round(NULL));
select 'SMOKE|p_round|2|' || typeof(p_round(NULL, NULL));
select 'SMOKE|p_rpad|3|' || typeof(p_rpad(NULL, NULL, NULL));
select 'SMOKE|p_rtrim|1|' || typeof(p_rtrim(NULL));
select 'SMOKE|p_rtrim|2|' || typeof(p_rtrim(NULL, NULL));
select 'SMOKE|p_secure_rand|0|' || typeof(p_secure_rand());
select 'SMOKE|p_secure_random|0|' || typeof(p_secure_random());
select 'SMOKE|p_secure_random|2|' || typeof(p_secure_random(NULL, NULL));
select 'SMOKE|p_sha1|1|' || typeof(p_sha1(NULL));
select 'SMOKE|p_sha256|1|' || typeof(p_sha256(NULL));
select 'SMOKE|p_sha512|1|' || typeof(p_sha512(NULL));
select 'SMOKE|p_sign|1|' || typeof(p_sign(NULL));
select 'SMOKE|p_sin|1|' || typeof(p_sin(NULL));
select 'SMOKE|p_split|2|' || typeof(p_split(NULL, NULL));
select 'SMOKE|p_split|3|' || typeof(p_split(NULL, NULL, NULL));
select 'SMOKE|p_split_part|3|' || typeof(p_split_part(NULL, NULL, NULL));
select 'SMOKE|p_split_to_multimap|3|' || typeof(p_split_to_multimap(NULL, NULL, NULL));
select 'SMOKE|p_spooky_hash_v2_32|1|' || typeof(p_spooky_hash_v2_32(NULL));
select 'SMOKE|p_spooky_hash_v2_64|1|' || typeof(p_spooky_hash_v2_64(NULL));
select 'SMOKE|p_sqrt|1|' || typeof(p_sqrt(NULL));
select 'SMOKE|p_starts_with|2|' || typeof(p_starts_with(NULL, NULL));
select 'SMOKE|p_strpos|2|' || typeof(p_strpos(NULL, NULL));
select 'SMOKE|p_strpos|3|' || typeof(p_strpos(NULL, NULL, NULL));
select 'SMOKE|p_strrpos|2|' || typeof(p_strrpos(NULL, NULL));
select 'SMOKE|p_strrpos|3|' || typeof(p_strrpos(NULL, NULL, NULL));
select 'SMOKE|p_substr|2|' || typeof(p_substr(NULL, NULL));
select 'SMOKE|p_substr|3|' || typeof(p_substr(NULL, NULL, NULL));
select 'SMOKE|p_t_cdf|2|' || typeof(p_t_cdf(NULL, NULL));
select 'SMOKE|p_tan|1|' || typeof(p_tan(NULL));
select 'SMOKE|p_tanh|1|' || typeof(p_tanh(NULL));
select 'SMOKE|p_to_base|2|' || typeof(p_to_base(NULL, NULL));
select 'SMOKE|p_to_base32|1|' || typeof(p_to_base32(NULL));
select 'SMOKE|p_to_base64|1|' || typeof(p_to_base64(NULL));
select 'SMOKE|p_to_base64url|1|' || typeof(p_to_base64url(NULL));
select 'SMOKE|p_to_big_endian_32|1|' || typeof(p_to_big_endian_32(NULL));
select 'SMOKE|p_to_big_endian_64|1|' || typeof(p_to_big_endian_64(NULL));
select 'SMOKE|p_to_hex|1|' || typeof(p_to_hex(NULL));
select 'SMOKE|p_to_ieee754_32|1|' || typeof(p_to_ieee754_32(NULL));
select 'SMOKE|p_to_ieee754_64|1|' || typeof(p_to_ieee754_64(NULL));
select 'SMOKE|p_to_utf8|1|' || typeof(p_to_utf8(NULL));
select 'SMOKE|p_trail|2|' || typeof(p_trail(NULL, NULL));
select 'SMOKE|p_trim|1|' || typeof(p_trim(NULL));
select 'SMOKE|p_trim|2|' || typeof(p_trim(NULL, NULL));
select 'SMOKE|p_truncate|1|' || typeof(p_truncate(NULL));
select 'SMOKE|p_truncate|2|' || typeof(p_truncate(NULL, NULL));
select 'SMOKE|p_upper|1|' || typeof(p_upper(NULL));
select 'SMOKE|p_url_decode|1|' || typeof(p_url_decode(NULL));
select 'SMOKE|p_url_encode|1|' || typeof(p_url_encode(NULL));
select 'SMOKE|p_url_extract_fragment|1|' || typeof(p_url_extract_fragment(NULL));
select 'SMOKE|p_url_extract_host|1|' || typeof(p_url_extract_host(NULL));
select 'SMOKE|p_url_extract_parameter|2|' || typeof(p_url_extract_parameter(NULL, NULL));
select 'SMOKE|p_url_extract_path|1|' || typeof(p_url_extract_path(NULL));
select 'SMOKE|p_url_extract_port|1|' || typeof(p_url_extract_port(NULL));
select 'SMOKE|p_url_extract_protocol|1|' || typeof(p_url_extract_protocol(NULL));
select 'SMOKE|p_url_extract_query|1|' || typeof(p_url_extract_query(NULL));
select 'SMOKE|p_uuid|0|' || typeof(p_uuid());
select 'SMOKE|p_weibull_cdf|3|' || typeof(p_weibull_cdf(NULL, NULL, NULL));
select 'SMOKE|p_width_bucket|4|' || typeof(p_width_bucket(NULL, NULL, NULL, NULL));
select 'SMOKE|p_wilson_interval_lower|3|' || typeof(p_wilson_interval_lower(NULL, NULL, NULL));
select 'SMOKE|p_wilson_interval_upper|3|' || typeof(p_wilson_interval_upper(NULL, NULL, NULL));
select 'SMOKE|p_word_stem|1|' || typeof(p_word_stem(NULL));
select 'SMOKE|p_word_stem|2|' || typeof(p_word_stem(NULL, NULL));
select 'SMOKE|p_xxhash64|1|' || typeof(p_xxhash64(NULL));
select 'SMOKE|p_xxhash64|2|' || typeof(p_xxhash64(NULL, NULL));

select 'SECTION|edge-cases';
select 'EDGE|numeric_abs|' || p_abs(-5);
select 'EDGE|numeric_acos|' || round(p_acos(0.5), 6);
select 'EDGE|numeric_asin|' || round(p_asin(0.5), 6);
select 'EDGE|numeric_atan2|' || round(p_atan2(1,1), 6);
select 'EDGE|numeric_factorial|' || p_factorial(5);
select 'EDGE|numeric_from_base|' || p_from_base('ff', 16);
select 'EDGE|numeric_to_base|' || p_to_base(255, 16);
select 'EDGE|numeric_mod|' || p_mod(10, 3);
select 'EDGE|numeric_round_n|' || p_round(2.345, 2);
select 'EDGE|numeric_truncate_n|' || p_truncate(2.345, 2);
select 'EDGE|numeric_width_bucket|' || p_width_bucket(0.1, 0.0, 1.0, 10);
select 'EDGE|numeric_normal_cdf|' || round(p_normal_cdf(0.0, 1.0, 0.0), 6);
select 'EDGE|numeric_inverse_normal|' || round(abs(p_inverse_normal_cdf(0.0, 1.0, 0.5)), 6);
select 'EDGE|bitwise_and|' || p_bitwise_and(12, 10);
select 'EDGE|bitwise_not|' || p_bitwise_not(0);
select 'EDGE|bitwise_shift_left|' || p_bitwise_shift_left(3, 2, 8);
select 'EDGE|text_lower|' || p_lower('HeLLo');
select 'EDGE|text_upper|' || p_upper('hello');
select 'EDGE|text_length|' || p_length('héllo');
select 'EDGE|text_bit_length|' || p_bit_length('abc');
select 'EDGE|text_codepoint|' || p_codepoint('A');
select 'EDGE|text_lpad|' || p_lpad('abc', 5, 'x');
select 'EDGE|text_rpad|' || p_rpad('abc', 5, 'x');
select 'EDGE|text_trim|' || p_trim('  hi  ');
select 'EDGE|text_replace|' || p_replace('abcabc', 'ab', 'X');
select 'EDGE|text_replace_first|' || p_replace_first('abcabc', 'ab', 'X');
select 'EDGE|text_split|' || p_split('a,b,c', ',');
select 'EDGE|text_split_part|' || p_split_part('a,b,c', ',', 2);
select 'EDGE|text_split_to_multimap|' || p_split_to_multimap('a=1;a=2;b=3', ';', '=');
select 'EDGE|text_strpos|' || p_strpos('abcabc', 'ab', 2);
select 'EDGE|text_strrpos|' || p_strrpos('abcabc', 'ab', 2);
select 'EDGE|text_substr_negative|' || p_substr('abcdef', -3, 2);
select 'EDGE|text_to_utf8|' || hex(p_to_utf8('Hi'));
select 'EDGE|text_trail|' || p_trail('abcdef', 2);
select 'EDGE|text_word_stem|' || p_word_stem('running');
select 'EDGE|text_from_utf8|' || p_from_utf8(x'6869');
select 'EDGE|text_from_utf8_replace|' || p_from_utf8(x'ff', '?');
select 'EDGE|text_normalize_nfd_len|' || p_length(p_normalize('é', 'NFD'));
select 'EDGE|text_hamming|' || p_hamming_distance('abc', 'axc');
select 'EDGE|text_levenshtein|' || p_levenshtein_distance('kitten', 'sitting');
select 'EDGE|regex_like|' || p_regexp_like('abc123', '[a-z]+[0-9]+');
select 'EDGE|regex_extract|' || p_regexp_extract('abc123', '([a-z]+)([0-9]+)', 2);
select 'EDGE|regex_extract_all|' || p_regexp_extract_all('ab12cd34', '([0-9]+)', 1);
select 'EDGE|regex_replace|' || p_regexp_replace('abc123', '[0-9]+', 'X');
select 'EDGE|regex_split|' || p_regexp_split('a1b2c', '[0-9]');
select 'EDGE|binary_concat_text|' || p_concat('a', 'b', 'c');
select 'EDGE|binary_concat_blob|' || hex(p_concat(x'AA', x'BB'));
select 'EDGE|binary_to_hex|' || p_to_hex(x'68656c6c6f');
select 'EDGE|binary_from_hex|' || hex(p_from_hex('68656c6c6f'));
select 'EDGE|binary_to_base64|' || p_to_base64(x'68656c6c6f');
select 'EDGE|binary_from_base64|' || hex(p_from_base64('aGVsbG8='));
select 'EDGE|binary_to_base32|' || p_to_base32(x'68656c6c6f');
select 'EDGE|binary_from_base32|' || hex(p_from_base32('NBSWY3DP'));
select 'EDGE|binary_to_base64url|' || p_to_base64url(x'68656c6c6f');
select 'EDGE|binary_from_base64url|' || hex(p_from_base64url('aGVsbG8'));
select 'EDGE|binary_length_blob|' || p_length(x'00ff');
select 'EDGE|binary_reverse_blob|' || hex(p_reverse(x'010203'));
select 'EDGE|binary_lpad_blob|' || hex(p_lpad(x'ab', 4, x'00'));
select 'EDGE|binary_rpad_blob|' || hex(p_rpad(x'ab', 4, x'00'));
select 'EDGE|binary_substr_blob|' || hex(p_substr(x'01020304', 2, 2));
select 'EDGE|binary_crc32|' || p_crc32(x'68656c6c6f');
select 'EDGE|hash_md5|' || hex(p_md5(x'616263'));
select 'EDGE|hash_sha1|' || hex(p_sha1(x'616263'));
select 'EDGE|hash_sha256|' || hex(p_sha256(x'616263'));
select 'EDGE|hash_sha512_len|' || length(p_sha512(x'616263'));
select 'EDGE|hash_hmac_sha256_len|' || length(p_hmac_sha256(x'616263', x'6b6579'));
select 'EDGE|hash_murmur3_len|' || length(p_murmur3_x64_128(x'616263'));
select 'EDGE|hash_xxhash64_len|' || length(p_xxhash64(x'616263'));
select 'EDGE|hash_spooky64_len|' || length(p_spooky_hash_v2_64(x'616263'));
select 'EDGE|binary_from_be32|' || p_from_big_endian_32(x'0000002a');
select 'EDGE|binary_from_be64|' || p_from_big_endian_64(x'000000000000002a');
select 'EDGE|binary_to_be32|' || hex(p_to_big_endian_32(42));
select 'EDGE|binary_to_be64|' || hex(p_to_big_endian_64(42));
select 'EDGE|binary_from_ieee32|' || round(p_from_ieee754_32(x'3f800000'), 6);
select 'EDGE|binary_from_ieee64|' || round(p_from_ieee754_64(x'3ff0000000000000'), 6);
select 'EDGE|binary_to_ieee32|' || hex(p_to_ieee754_32(1.0));
select 'EDGE|binary_to_ieee64|' || hex(p_to_ieee754_64(1.0));
select 'EDGE|url_host|' || p_url_extract_host('https://example.com:8443/path?q=1#f');
select 'EDGE|url_port|' || p_url_extract_port('https://example.com:8443/path?q=1#f');
select 'EDGE|url_protocol|' || p_url_extract_protocol('https://example.com:8443/path?q=1#f');
select 'EDGE|url_path|' || p_url_extract_path('https://example.com:8443/path?q=1#f');
select 'EDGE|url_query|' || p_url_extract_query('https://example.com:8443/path?q=1#f');
select 'EDGE|url_fragment|' || p_url_extract_fragment('https://example.com:8443/path?q=1#f');
select 'EDGE|url_parameter|' || p_url_extract_parameter('https://example.com:8443/path?q=1#f', 'q');
select 'EDGE|url_encode|' || p_url_encode('a b');
select 'EDGE|url_decode|' || p_url_decode('a+b');
select 'EDGE|ip_prefix|' || p_ip_prefix('10.1.2.3', 16);
select 'EDGE|ip_prefix_collapse|' || p_ip_prefix_collapse('10.0.0.0/8,10.1.0.0/16,192.168.0.0/16');
select 'EDGE|ip_prefix_subnets|' || p_ip_prefix_subnets('10.1.0.0/16', 18);
select 'EDGE|ip_subnet_min|' || p_ip_subnet_min('10.1.0.0/30');
select 'EDGE|ip_subnet_max|' || p_ip_subnet_max('10.1.0.0/30');
select 'EDGE|ip_subnet_range|' || p_ip_subnet_range('10.1.0.0/30');
select 'EDGE|ip_is_private|' || p_is_private_ip('10.1.2.3');
select 'EDGE|ip_is_subnet_of_ip|' || p_is_subnet_of('10.1.0.0/16', '10.1.2.3');
select 'EDGE|ip_is_subnet_of_prefix|' || p_is_subnet_of('10.0.0.0/8', '10.1.0.0/16');
select 'EDGE|uuid_len|' || length(p_uuid());
select 'EDGE|uuid_regex|' || p_regexp_like(p_uuid(), '^[0-9a-f-]{36}$');
select 'EDGE|edge_split_part_missing|' || typeof(p_split_part('a,b', ',', 3));
select 'EDGE|edge_url_port_none|' || typeof(p_url_extract_port('https://example.com'));
select 'EDGE|edge_ip_family_mismatch|' || p_is_subnet_of('10.0.0.0/8', '2001:db8::/32');
select 'EDGE|edge_trail_zero|' || p_trail('abc', 0);
